version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: \${DATABASE_NAME}
      POSTGRES_USER: \${DATABASE_USERNAME}
      POSTGRES_PASSWORD: \${DATABASE_PASSWORD}
    ports:
      - "\${DATABASE_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: base
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DATABASE_NAME: \${DATABASE_NAME}
      DATABASE_USERNAME: \${DATABASE_USERNAME}
      DATABASE_PASSWORD: \${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: \${DATABASE_PORT}
    depends_on:
      - db

  tests:
    build:
      context: .
      target: base
    command: npm test
    environment:
      DATABASE_NAME: \${DATABASE_NAME}
      DATABASE_USERNAME: \${DATABASE_USERNAME}
      DATABASE_PASSWORD: \${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: \${DATABASE_PORT}
    depends_on:
      - db

volumes:
  db_data:
