services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/blog_db
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    command: npm test
    depends_on:
      - db

volumes:
  db-data:
